-- Karta Kurdî / Supabase database
create table if not exists public.digital_cards (
  id bigint generated by default as identity primary key,
  card_id text unique not null,
  name text not null,
  surname text not null,
  gender text,
  region text,
  dialect text,
  country text,
  visibility text not null default 'public' check (visibility in ('public','private')),
  created_at timestamptz not null default now()
);

alter table public.digital_cards enable row level security;

-- Public users can create a card.
create policy "anyone can create cards"
on public.digital_cards for insert
to anon, authenticated
with check (true);

-- Public cards can be viewed.
create policy "public cards are readable"
on public.digital_cards for select
to anon, authenticated
using (visibility = 'public');

-- Important: do NOT create a policy allowing anonymous update/delete.
